load("19_cpan_workflow.RData")
pdf("cpan.pdf")


png("tests.png")
plot(ordered(data$install_CPAN_always_test_run),main="Always run the tests")
dev.off()
png("force.png")
plot(ordered(data$freq_force_install_CPAN_mods_after_test_fail),main="Force install after test failures")
dev.off()
png("understand.png")
plot(ordered(data$try_to_understand_why_tests_fail_before_force_install), main="Try to understand why tests fail before I force install")
dev.off()
png("report.png")
plot(ordered(data$report_test_fails_thru_approp_channels), main="Report failing tests by the appropriate channel")
dev.off()

library(R2HTML)
HTMLStart(".",'index', HTMLframe=FALSE,Title="CPAN Usage", autobrowse=FALSE)
HTML.title("When Installing a CPAN module I ...", HR=1)
HTMLInsertGraph("tests.png")
HTMLInsertGraph("force.png")
HTMLInsertGraph("understand.png")
HTMLInsertGraph("report.png")
HTMLStop()
