load("16_opinions.RData")
library(Hmisc)
data[data==1] = NA
data <- data-1
describe(data)
data.clean<- na.omit(data)
f2=factanal(data.clean,2,rotation="varimax")
load = loadings(f2)
print(load)
quartz()
plot(load)
# identify(load,labels=names(data.clean))
me <- data[c(1,3,4,5,10,11,12,13,14,15,16,17)]
work <- data[c(2,6,7,8,9)]

pdf("personal.pdf")
par(mfrow=c(3,2))
plot(ordered(data$perl_cutting_edge_programming_language),main="cutting edge")
plot(ordered(data$perl_good_language_for_startup),main="startup")
plot(ordered(data$perl_easy_to_maintain),main="maintainable")
plot(ordered(data$perl_code_scales_well),main="scales")
plot(ordered(data$perl_good_first_programming_language),main="first language")
plot(ordered(data$perl_good_tool_for_beginners),main="beginners")
dev.off()

pdf("personal2.pdf")
par(mfrow=c(3,2))
plot(ordered(data$perl_good_tool_early_career_programmers),main="early career")
plot(ordered(data$perl_good_tool_experienced_programmers),main="experienced")
plot(ordered(data$perl_good_tool_system_administrators),main="sysadmins")
plot(ordered(data$perl_good_tool_network_engineers),main="network")
plot(ordered(data$perl_good_tool_embedded_systems_programmers),main="embedded")
plot(ordered(data$perl_good_tool_applications_programmers),main="applications")
dev.off()
pdf("work.pdf")
par(mfrow=c(3,2))
plot(ordered(data$perl_encouraged_at_workplace),main="encouraged")
plot(ordered(data$management_encourages_perl_for_new_projects),main="new projects")
plot(ordered(data$management_views_perl_as_cutting_edge),main="cutting edge")
plot(ordered(data$management_views_perl_as_easy_to_maintain),main="maintainable")
plot(ordered(data$management_thinks_perl_scales_well),main="scales")
dev.off()
